### ISSUE TITLE
Metrics plots

### ISSUE THREAD

**Issue by l0ka** [bjpop/varlap#7]
Hi @bjpop, thank you for this very nice and useful tool. 
I just started to use it and I'd like to make some summary plots to have a better overview of the different metrics in the varlap output. I noticed you removed the code for plotting. Are you planning to re-implement it? Is there another tool/package to replace it?
Thank you!

**Comment by bjpop** [comment]
Hi @l0ka 

Thanks for trying Varlap.

I've removed the plotting code because I now have a more general-purpose command line plotting program called Hatch that fulfils this role and is usable outside of Varlap:

    https://github.com/bjpop/hatch

User docs (work in progress) for hatch:

    https://hatch.readthedocs.io/

I'm actively working on both Varlap and Hatch, so if you use them and have any feedback or requests for features please put them on Github issues. That would be greatly appreciated. Also don't be afraid to ask for help with using these tools. I'm very happy to have people using them.

Cheers!

**Comment by l0ka** [comment]
@bjpop thank you very much for the quick reply! I'll try `hatch` asap and I'll be happy to provide you my feedback!

Cheers!
